### ISSUE TITLE
Add backend for chores functionality

### ISSUE THREAD

**Issue by jbea599** [SOFTENG701G1/Flatmate-Management-System#148]
**User story**
As a developer, I want the chores components in the front end, to be linked up to back-end APIs for it, enabling new chores to actually be added to the flat in the database, as well as displayed in the chores table. Currently it is front-end only.

**Acceptance criteria**

- [ ] Users can add new chores and it is stored in the database
- [ ] Chores table retrieves actual chores from database to show
- [ ] User can mark chores as completed

**Additional context**
N/A

**Comment by SeanSpires** [comment]
Updated the issue so it includes the marking chores as complete functionality.

**Comment by SeanSpires** [comment]
This issue seems like quite a large piece of work. Since this issue was here before we took over the project, should we split this issue up or leave it as it is? For example, this issue encompasses creating the chore API controller and setting up the chore repository among other things.

**Comment by lken274** [comment]
I think a chore repository is already covered by #86. We should definitely have an "endpoints" issue, maybe several. We can leave this up as the overall issue and depend it on all the others.

**Comment by lken274** [comment]
Issue separated into several smaller issues.
