### ISSUE TITLE
Add ability to change user details

### ISSUE THREAD

**Issue by NathanMills1** [SOFTENG701G1/Flatmate-Management-System#165]
**User story**
As a user, I want to be able to edit my user details, in order to change the information my flat mates can see about me.

**Acceptance criteria**
- API defined (and updated in wiki) to support editing user details
- Upon editing details and saving, changes are saved to database

**Comment by williamlixu** [comment]
This issue changed to cover just the back-end to support this. The functionality will be accessible from the profile page in issue #233
