### ISSUE TITLE
Integrate chores page with database (implement GET chores API)

### ISSUE THREAD

**Issue by maddiebeagley** [SOFTENG701G1/Flatmate-Management-System#181]
**User story**
As a user, I want to see an up-to-date display of the chores my flat and I are currently responsible for on the chores page of the application so that I know who is responsible for what. 

**Acceptance criteria**
- All of the chores that I am currently responsible for are visible on the chores page
- Only chores I am responsible for are displayed on the chores page
- All the chores my flatmates are responsible for are visible on the chores page
- I can tell which chores are assigned to which flatmates

**Additional context**
This will likely share the API required for issue #180.

**Comment by lken274** [comment]
This issue would be better listed as two separate issues (backend and frontend). I am closing this and will make a corresponding backend issue.
