### ISSUE TITLE
Disable the reset password button once pressed

### ISSUE THREAD

**Issue by jhsi517** [SOFTENG701G1/Flatmate-Management-System#192]
**User story**
As a user, I want to not be able to send multiple reset password instructions a so that I wont receive multiple emails and confuse me.

**Acceptance criteria**
 - User not able to submit another reset password request when the email is still getting sent

**Additional context**
N/A

**Comment by mini** [comment]
Maybe only for a short time? So they can try again

**Comment by jhsi517** [comment]
Yes, once the API responded, the button should either be available again if there was an error, or bring user to the next page saying that the email has been sent :D 

sorry, should have clarified it in the issue
