### ISSUE TITLE
Create documentation for new chore API endpoints

### ISSUE THREAD

**Issue by SeanSpires** [SOFTENG701G1/Flatmate-Management-System#214]
**Describe the change**
We need documentation on the API endpoints for the chore controller alongside details on the relevant JSON objects.

**Why is this happening**
We need this change so the front-end team has a point of reference for how to interact with the API.

**Comment by lken274** [comment]
https://github.com/SOFTENG701G1/Flatmate-Management-System/wiki/Chores-API

Please review

**Comment by williamlixu** [comment]
LGTM!
