### ISSUE TITLE
Update Authorisation section in the Testing wiki

### ISSUE THREAD

**Issue by dder725** [SOFTENG701G1/Flatmate-Management-System#221]
**Describe the change**
https://github.com/SOFTENG701G1/Flatmate-Management-System/wiki/Writing-Tests-that-require-JWT-Authorization - the information on this page is outdated. Classnames and the general approach should be updated in accordance with how it is currently being done in the testing suites.

**Why is this happening**
To ensure that developers can easily add authorisation to their unit tests.

**Comment by williamlixu** [comment]
I have now updated the wiki page, please have a look to ensure it makes sense! You can close this issue if it looks good.

**Comment by margeobur** [comment]
Looks good! Closing issue now.
