### ISSUE TITLE
Add member to flat

### ISSUE THREAD

**Issue by williamlixu** [SOFTENG701G1/Flatmate-Management-System#230]
**User story**
As a user I want to be able to add another user (by username) to my flat on the website.

**Acceptance criteria**
- Able to open the website, go to the members page and search for a user by username.
- Pressing add will make the API call to the back-end to add username to flat
- Flat member shows up in flat if successful
- Appropriate error message e.g. "User not found" shown if unsucessful

**Additional context**
- Some form of validation may be needed e.g. member not in a flat already. If this gets complex it should be done on the back-end and logged as a new issue.

**Comment by rfro377** [comment]
@williamlixu 
I have got the adding user working, I just need to add some error messaging for the different return codes. The pull request will be up in a few days.

**Comment by williamlixu** [comment]
Sweet as, sounds like we are on track!
