### ISSUE TITLE
Implement API to remove members from flat

### ISSUE THREAD

**Issue by williamlixu** [SOFTENG701G1/Flatmate-Management-System#231]
**User story**
As a user I want to be able to remove members from my flat if they move out.

**Acceptance criteria**
- Endpoint defined (and wiki updated) to support removing members from flat
- When the endpoint is called with a valid input of the user to remove, it removes member from flat in database.
- Unit tests to ensure this functionality works as expected

**Additional context**
Front-end for this issue is #232

**Comment by tant836** [comment]
Could this API use the username and not the ID?

**Comment by williamlixu** [comment]
Closing as duplicate of #53, which has already been completed.
