### ISSUE TITLE
[BUG] Members, Payments and Dashboard pages don't load properly

### ISSUE THREAD

**Issue by tant836** [SOFTENG701G1/Flatmate-Management-System#244]
**Describe the bug**
Multiple pages don't seem to load properly and errors are thrown on the console when they are opened.

**Severity**
Mild

**To Reproduce**
1. Open the webpage following the guide on the readme
2. Click on members page (This is the most obvious)
3. Page is stuck on the loading screen indefinitely

This error occurred because I pulled from master, so I was no longer logged in. However, my web browser still had the webpage in cache, so all the components fetched from the backend would not load.

**Expected behaviour**
The pages are supposed to load. For the members page, you should be able to see flat members' information.

**Actual behaviour**
For the members page it is stuck on loading indefinitely, for other pages, some info does not load

**Environment:**
 - OS:  Windows 10
 - Browser chrome

**Possible solution:**
logging out and logging in again should solve this problem.

**Comment by williamlixu** [comment]
Will have a look and see if I can reproduce first

**Comment by williamlixu** [comment]
Hmmm, everything still seems to working for me, wonder if it's something wrong with your local build? I can try help figure it out, maybe first try making sure you have the latest version of master and then doing a fresh build.

**Comment by tant836** [comment]
logging out and in again fixes this issue, closed
