### ISSUE TITLE
[BUG] Backend fails to build - Conflicting method/path combination "DELETE api/Chore/{id}"

### ISSUE THREAD

**Issue by jake-good** [SOFTENG701G1/Flatmate-Management-System#256]
**Describe the bug**
Cannot run back end, error caused by conflicting Endpoint method/path combo at the delete chore endpoint

**Severity**
Breaks Everything

**To Reproduce**
1. Run Backend

**Expected behaviour**
Backend runs successfully

**Actual behaviour**
Backend fails to run - error in output: Conflicting method/path combination "DELETE api/Chore/{id}"

**Screenshots**

**Environment:**
Windows 10 - Chrome

**Possible solution:**

**Additional context**

**Comment by williamlixu** [comment]
Need this to be quickly merged done so we could continue doing work but the issue was verified with @misl000, @icam308 ,@pabloSushibar and @vee-christella while coding together :)
